config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "shifts#index"
  resources :shifts
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true, length: {maximum: 10}
  validates :number, presence: true, uniqueness: true, length: {maximum: 10}
  validates :email, uniqueness: true

  def email_required?
    false
  end

  def email_changed?
    false
  end

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #strong parametersを設定し、nameを許可
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :password, :password_confirmation, :number) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:name, :password, :password_confirmation, :number) }
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    date_today
  end

  def create
    shift = Shift.new(event_params)
    shift.save!
    @shifts = Shift.where(user_id: current_user.id)
end

def update
    shift = Shift.find(params[:id])
    @shifts = Shift.where(user_id: current_user.id)
    shift.update(shift_params)
end

def destroy
    @user = User.find(params[:id])
    shift = Shift.find(params[:id])
    shift.destroy
    redirect_to user_path(@user)
end

private
def shift_params
    params.require(:shift).permit(:title, :start, :end, :user_id, :body)
end

  def date_today
    @now = Date.today
    @wday_jan = ["月","火","水","木","金","土","日"]
    @this_year = @now.year
    @this_month = @now.month


    @first_day = @now.beginning_of_month
    @last_day = (@first_day + (7-@first_day.wday))
    @week_period = (@first_day..@last_day)

    @last_day2 = (@last_day + (7-@last_day.wday))
    @week_period2 = ((@last_day+1)..@last_day2)

    @last_day3 = (@last_day2 + (7-@last_day2.wday))
    @week_period3 = ((@last_day2+1)..@last_day3)

    @last_day4 = (@last_day3 + (7-@last_day3.wday))
    @week_period4 = ((@last_day3+1)..@last_day4)

    @last_day5 = (@last_day4 + (7-@last_day4.wday))
    @week_period5 = ((@last_day4+1)..@last_day5)

    @last_day6 = (@last_day5 + (7-@last_day5.wday))
    @week_period6 = ((@last_day5+1)..@last_day6)

    

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shift</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %>
              </li>
            </ul>
          </span>
      <li><%= link_to current_user.name, "#", class: "user-nickname" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">PicTweet</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

app/views/shifts/_edit.html.erb
<% events.each do |event| %>
    <div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-nm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">スケジュール編集</h4>
                </div>
                <div class="modal-body">
                    <div  class="col">
                        <%= form_with(model: event, url: users_event_path(event), method: :put) do |f| %>
                            <p>
                                <span>タイトル</span>
                                <span id="inputTitle" value=""><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                            </p>
                            <span>開始日時</span>
                            <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                            <span>終了日時</span>
                            <span><%= f.datetime_field  :end, placeholder: "XXXX-XX-XX", class:"field" %></span>
                            <span><br>
                                詳細
                                <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %>
                            </span>
                            <div class="modal-footer">
                                <%= f.hidden_field :user_id, :value => current_user.id %>
                                <%= f.submit "編集する", class: "btn btn-primary" %>
                                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shifts/index.html.erb
<%= render "shared/header" %>
シフト一覧表
<div class="schedule_title">
    <h1>Schedule Board</h1>
</div>

<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <title>Calendar</title>
</head>
<body>
  <table>
    <thead>
      <tr>
        <th id="prev">&laquo;</th>
        <th id="title" colspan="5">2005/05</th>
        <th id="next">&raquo;</th>
      </tr>
      <tr>
        <th>Sun</th>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
    <tfoot>
      <tr>
        <td id="today" colspan="7">Today</td>
      </tr>
    </tfoot>
  </table>

</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン画面へ", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録画面", new_registration_path(resource_name) %><br />
<% end %>


<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h3 class="text-center">カレンダー</h3>
<!-- カレンダーの表示 -->
<div id="calendar"></div>
<!-- もしユーザーがログインしていたら -->
<% if user_signed_in? %>
    <!-- ページのparams.idがログインユーザー.idと同じなら -->
    <% if @user.id == current_user.id %>
        <div id="inputScheduleForm" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-nm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">スケジュール登録</h4>
                    </div>
                    <div class="modal-body">
                        <%= form_with model: @shifts, url: shifts_path do |f| %>
                            <div  class="col">
                                    <p>
                                        <span>タイトル</span>
                                        <span><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                                    </p>
                                    <span>開始日時</span>
                                    <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                                    <span>終了日時</span>
                                    <span><%= f.datetime_field :end, placeholder: "XXXX-XX-XX", class:"field" %></span><br>
                                    <span>詳細
                                    <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %></span>
                            </div>
                            <div class="modal-footer">
                                <%= f.submit "登録する", class: "btn btn-primary" %>
                                <%= f.hidden_field :user_id, :value => current_user.id %>
                                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
<!-- 編集 ------------------------------------------------------------------>
        <div id="inputEditForm">
            <%= render 'shifts/edit', shifts: @shifts %>
        </div>
    <% end %>
<% end %>
    <script>
    // CRUDを行う際にCSRF対策のtokenを発行
        $(document).ready(function() {
        var prepare = function(options, originalOptions, jqXHR) {
          var token;
          if (!options.crossDomain) {
            token = $('meta[name="csrf-token"]').attr('content');
            if (token) {
              return jqXHR.setRequestHeader('X-CSRF-Token', token);
            }
          }
        };
        }
        )

        // カレンダー表示
        $('#calendar').fullCalendar ({
            header: {
                left: 'prev,next today',
                center: 'month,agendaWeek,agendaDay',
                right: 'title'
            },

            buttonText: {
                  prev: "<",
                  next: ">"
            },

            timezone: 'UTC',
            events: '/users/shifts.json',
            navLinks: true,
            selectable: true,
            selectHelper: true,
            // 日付クリック
            dayClick : function ( date , jsEvent , view ) {
                $('#inputScheduleForm').modal('show');
                },

            // event クリックで編集、削除
            eventClick : function(event, jsEvent , view) {
                jsEvent.preventDefault();
                $(`#inputScheduleEditForm${shift.id}`).modal('show');
            },

            eventMouseover : function(shift, jsEvent , view) {
                jsEvent.preventDefault();
            }
        })

    </script>